### ISSUE TITLE
Why mmap

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/pyeventio#10]
Can you explain why you used an `mmap` object? What is the advantage over a standard python file object?

I stumbled into this question because `np.fromfile` cannot handle a `mmap` object

**Comment by dneise** [comment]
No idea, looks like (premature?) optimization to me. One could refactor it back into a srd file object and see if there's a problem... 

I wonder how to document such optimizations, in case one reviews code months later and wonders what a certain piece is about...
