### ISSUE TITLE
Import error: cannot import Event

### ISSUE THREAD

**Issue by morcuended** [fact-project/pyeventio#110]
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-76ba1ff7ed09> in <module>
----> 1 from eventio.simtel import (
      2     CameraSettings,
      3     Event,
      4     TelescopeEvent,
      5     ADCSums

ImportError: cannot import name 'Event'
```

**Comment by dneise** [comment]
Hello Daniel :-) thanks for playing around as promised :-)

This ImportError occurs because there is nothing named `Event` in eventio.simtel.
One way to look at the classes defined in `eventio.simtel` might be:

    from eventio import simtel
    print(simtel.__all__)


May I ask what it is you are trying to accomplish here? Looks to me like you are done playing with the high level `SimTelFile` and now your want to look into the guts of a file and dig around yourself. That is great!

**Comment by dneise** [comment]
Ah ... I just searched for `Event` in the codebase and found it mentioned in several places, like. e.g. in `examples/plot_astri.py` and `examples/plot_events.py` as well as in the doc-strings of two functions in `search_utils.py`. 

So we have to repair these doc-strings and examples.

In the meantime I wanted to propose you might want to try `eventio_print_structure <path>` to learn about the correct class names. But I found also a tiny bug in that tool. I opened and issue (#111) about this already.

**Comment by MaxNoe** [comment]
Docs and examples fixed in #114

**Comment by morcuended** [comment]
Yes, Domink.

I am producing some simtel files containing only fluorescence light, which gives no signal triggered by itself with the usual telescopes config files. Therefore there are no events to load (e.g. with ctapipe).

It seems that the way to access to the info within is via this event object containing MC info. The file contains some metadata actually (simtelarray config parameters...), though.

**Comment by MaxNoe** [comment]
You might want to look into what i proposed here #117, maybe you want to also look into the `iact.PhotoElectrons`?

**Comment by MaxNoe** [comment]
What do you want to know? True Photons hitting the camera of each telescope?
