### ISSUE TITLE
typo in PixelList.__repr__: self.telescopes_id  <--- no plural s here.

### ISSUE THREAD

**Issue by dneise** [fact-project/pyeventio#111]
title says it all.

We should not only fix this but also write a test to make sure it does never occur again. 
I assume calling all repr of all objects in `gamma_test.simtel.gz` already calls a lot of the reprs.

**Comment by dneise** [comment]
This issue has some impact on #110 Since a user might want to use `eventio_print_structure` to learn about the structure and the real class names ob the objects in a file. But bugs in reprs bubble up into that tool.

**Comment by MaxNoe** [comment]
Fixed by merging #113
