### ISSUE TITLE
put this on PyPI

### ISSUE THREAD

**Issue by dneise** [fact-project/pyeventio#2]
I would love to push this to PyPI once we have at least a single test showing, that it can read a file and create a plot from it.

**Comment by MaxNoe** [comment]
Should we tag the current master as 0.2 and publish?

**Comment by dneise** [comment]
I think there is currently a PR open which we should discuss further on before the next tag.

**Comment by MaxNoe** [comment]
Really? I think this is usable right now and a pretty big step up from the last tag. This should be tagged  imho. 

The discussion in the pull request might be something for the version after that.

**Comment by MaxNoe** [comment]
At least tag it, maybe not upload it to pypi. We increased the version number. A version number should be tagged.

**Comment by dneise** [comment]
Tagging it makes total sense, I agree.

**Comment by mackaiver** [comment]
Anything going in with this btw? 
because 
`pip install pyeventio`

does not work as advertised in the README. (not that this would be an urgent problem or anything. just wanted to mention it.)

**Comment by dneise** [comment]
Ah this is because one has to omit the superfluous `py` and just type:

    pip install eventio

have a look here: https://pypi.python.org/pypi/eventio

We have to fix the README
