### ISSUE TITLE
tuples of (header, data) versus EventIOObject

### ISSUE THREAD

**Issue by dneise** [fact-project/pyeventio#20]
At the moment, the new low level API returns lists of 2-tuples 
- either like `(header, data)` 
- or like `(header, [(H,D), (H,D)]`

For this we (well it was basically me, who is to blame for this) introduced **two** new classes: `ObjectHeader` and `ObjectData`, where `ObjectHeader` is a simple `namedtuple` of some numers and `ObjectData` hides the actual "Data-Field" behind its `value` member. So none of the two objects is really "complex".

The user of this low level API will mostly check  `ObjectHeader.type`, `ObjectHeader.id` and `ObjectHeader.version` and then start parsing `ObjectData.value`. In her code it might look like this roughly.

``` python
with open('path', 'rb') as f:
    tree = object_tree(f)
    # the user knows exactly, where in the tree she wants to look
    some_object = tree[14][2] 
    if some_object[0].type == 1234:
        return np.array(some_object[1].value)
```

You see? these ugly brackets all over the place? Why can it not look like:

``` python
    if some_object.type == 1234:
        return np.array(some_object.value)
```

There is no name clash between the members of `ObjectHeader` and `ObjectData`, so we could combine all `(H, D)` into one "Object" or whatever name we like.

But how would now the return value of `object_tree` look like? clearly some kind of tree-like structure.
At the moment, we represent the tree basically as a like of lists, but not quite.
Trivially it would be a list of these `Object`s, where each objects `value`, could be either actual binary payload or another list of `Object`s, but then, this does not work:

```
some_object = tree[14][2] 
```

`tree` is a list so `tree[14]` works, but the result is an `Object` and `Object`s have no `__getitem__`. Why would they? Their purpose is to lower the typing effort of users to access header-like and data-like members without typing brackets and even having to remember if something was more a header-like or more data-like member. (Looking at you `length`, which is a header-like member at the moment, but might be data-like in the future).

---

I find it much easier to think about these problems by using examples. These examples I hope help showing any reader my state of mind and help finding wrong assumptions I made.

So for the moment I think of this tree (which might be returned by the current `object_tree` function). 

``` python
tree = [
  (H0, D0), # run header?
  (H1, [
    (H10, D10), # header of 1st event
    (H11, [
      (H110, D110), # photons of 1st telescope of 1st event
      (H111, D111), # photons of 2nd telescope of 1st event
    ]),
    (H12, D12), # foot of 1st event
  ]),
  (H2, D2), # run footer
]
```

This is, how the "trivial" `Objects` solution might look.

``` python
tree = [
  O0, # run header?
  O1, # an event?
  O2, # run footer
]
```

Nicer clearly ... but `Objects` combine list-like behaviour and their actual "being an eventio-object". This feels not very good when thinking about "Separation of Concerns" as I understand it. 

Another possibility would be, to let `list`s take care **entirely** of exposing the files hierarchical structure. E.g. like this:

``` python
tree = [
  O0, # run header?
  [
    O10, # header of 1st event
    [
      O110, # photons of 1st telescope of 1st event
      O111, # photons of 2nd telescope of 1st event
    ],
    O12, # foot of 1st event
  ],
  O2, # run footer
]
```

I like this much better than the previous version as it nicely separates concerns into "represent a tree" and "contain data, with a header telling me what the data is". This might be a nice picture, but something is missing. `tree[1]`, in the topmost version had a header, it was able to tell me about its version, type and id. Now `tree[1]` is just a `list`, which does not know anything about itself. So this is a problem here.
I think this problem reveals a question, I am unable to answer, and since I think it is somehow an important question, I draw a line and give it a catchy caption

---
## What are you doing there?

The question one has to answer in order to understand what interface is "best" is how one is going to use it. In particular I am interested in the tree-like structure eventio files have and the header information a sub-tree has. 

So my first fundamental assumption is: A user wants to find some "data" inside the file.
By "data" I mean these `D` things further up. The tree-like structure and the `H`-things are just there to help her in finding (and correctly interpreting) the `D`-things.

So hypothetical user questions dealing with info from `H`-things and the list-of-list-structure include:
- Give me the 73th `D` thing of type 1337, version 42 and id 17.
- How many things of type 17 are there, which also have a version of 3? And what ids do they have?

But what I see in my own code looks more like this:
- Give me the 1st thing. It must be of type 5, if not the file must be broken.
- `tree[1]` must be a list, otherwise the file is broken.
- `tree[2]` must not be a list, otherwise the file is broken.

So, from my **experience** the `H` things, which belong to sub-trees are not used by my code at all. 
So I feel quite an urge, to get rid of them. 

On the other hand, this lowest level API I am thinking about should maybe not hide any single byte of the file. So nothing should be dropped.

---
## Last but not least

Clearly in the eventio file standard this "Separation of Concerns" - as I understand it - is not held as high, as I would like it. Fair enough. So maybe one should simply reproduce the structure as it is.
So `Objects` do both:
- they organize the file itself
- and contain data. 

In case we like the list-of-list representation for a tree, the next logical step would be. The `Objects` inherit list-like behaviour and just add the data part, so I tried something like that here: df1ccc54514b4b7f9a17b57e5d7b035dd9bf68e6

**Comment by MaxNoe** [comment]
> tree is a list so tree[14] works, but the result is an Object and Objects have no __getitem__. Why would they

Because Objects can be containers and it's natural for a container to have `__getitem__`!

(I recently learned that `__` is called dunder by most python folks)
