### ISSUE TITLE
Windows incompatibility with mmap

### ISSUE THREAD

**Issue by matyro** [fact-project/pyeventio#27]
When you try  to use the readon on windows you get following error:

> E:\Programme\Anaconda3\lib\site-packages\eventio\base.py in __init__(self, path)
>    25  self.path = path
>    26  self.__file = open(path, 'rb')
>    ---> 27         self.__mm = mmap.mmap(self.__file.fileno(), 0, prot=mmap.PROT_READ)
>    28 
>    29         if path.endswith('.gz'):
>    AttributeError: module 'mmap' has no attribute 'PROT_READ'`

The reason for this is PROT_READ is not defined under windows, you need to use mmap.ACCESS_READ.

Additional the functions have a different syntax see:
https://docs.python.org/3/library/mmap.html
(windows version)
(unix version)

I hope that the windows version can be added.

A possible method is

> import platform
> if platform.system() == 'Windows':
>     self.__mm = mmap.mmap(self.__file.fileno(), 0, access=mmap.ACCESS_READ)
>else :
> ...

**Comment by dneise** [comment]
I think we dont need mmap at all. Its just in because I didn't know what I was doing in the beginning

**Comment by dneise** [comment]
Ah and in case it was in the code to improve Performance or so, it still has to be removed ö, because I failed to show in a test, that this performance is crucial. 

So who ever feels interested in this package should imho remove the mmap stuff for the sake of cleanliness.

**Comment by MaxNoe** [comment]
I personally refuse to add code like `if platform == "Windows"` and would also object to any merge introducing such code. It just gets a mess (or even more messy). 

I think removing `mmap` is the way to go.
