### ISSUE TITLE
Add support for more EventIO Object Types

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/pyeventio#5]
I will look into this. Hopefully it will be possible to generalize this to also be able to read `sim_tellarray` output.

**Comment by dneise** [comment]
Do you think, we should as a start and foundation for a ll this, collect documentation about Object Types we find in a /doc folder inside this repo? So we can in doc-strings and issue refer to something?

**Comment by MaxNoe** [comment]
Good idea

**Comment by MaxNoe** [comment]
General stuff works now. We could start writing support for new Objects.

**Comment by MaxNoe** [comment]
Most simtel objects got implemented in #36. If someone needs additional objects, please open a new issue per object type.
