### ISSUE TITLE
Support both endianness

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/pyeventio#6]
Edit: EventIO always claims that you can write items in both endiannesses. At the moment we only check for Objects which are written in native byteorder.

If I understood it correctly the 4 sync bytes tell the endianness of the following object. We do not test for this at the moment, correct?

**Comment by dneise** [comment]
You mean, test in unit tests? let me have a look ... nope we don't.

**Comment by MaxNoe** [comment]
Ah,, sorry. Wrong choice of words.

No, I mean test as in support for reading both like eventio always claims.

**Comment by dneise** [comment]
Ah, I see. Well this sync thing is checked, so at the moment the end user can see, if the endianess is 'normal'. That's all we do at the moment.

Surely this is something that can be improved

**Comment by dneise** [comment]
Is it a bug?

**Comment by MaxNoe** [comment]
Python 2 vs Python 3 is our decision. Supporting both endiannesses is kind of the point of EventIO (how ridiculous this might seem to us). 

For me it's a bug, because we do not follow the "file standard"

**Comment by dneise** [comment]
For me supporting big_endian data, is a feature, provided by this file standard. Just like FITS provides many features, not all FITS reader and writer implementations support all features. 
So at the moment, for me this is (just) a missing feature not a bug. 

A warning, telling the user, that a certain part of the file is big_endian and cannot be read is as long enough as we have no users with files containing big endian data.

**Comment by MaxNoe** [comment]
Ok. I do not know if there are big endian files in the wild. Maybe this is a won't fix.

**Comment by dneise** [comment]
also possible

**Comment by dneise** [comment]
also ... if somebody likes to implement this feature, just for the fun of it .... no problem ... I won't stand in peoples way ... (in case i sounded like that)

**Comment by MaxNoe** [comment]
Ok, you know what just happend? The first sim_telarray file I tried to open (the `gamma_test.simtel.gz` from the `ctapipe-extras` repository) is Big Endian.

Or at least the marker is:
```ipython
In [8]: struct.unpack('<l', bytearray.fromhex('378a1fd4'))
Out[8]: (-736130505,)
```

**Comment by dneise** [comment]
Which poses the question: why? Why would somebody on modern hardware go through the trouble of switching endianess before saving the data in a file, just because the file format allows for it?

**Comment by MaxNoe** [comment]
I'm confused. 

According to the `struct` docs: https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment
* '>' means big endian
* '<' means little endian

Default is native, which is little endian for my machine (and supposedly every other machine younger than 20 years).

On page 4 of the EventIO docs, Bernlohr writes, that the sync int should be `-736130505` if interpreted as signed integer.

At the moment we test for `d41f8a37`.

And that is, if i'm not mistaken, the BIG ENDIAN notation of `-736130505`:

```
In [28]: np.frombuffer(bytearray.fromhex('d41f8a37'), '>i4')
Out[28]: array([-736130505], dtype=int32)

In [29]: np.frombuffer(bytearray.fromhex('378a1fd4'), '<i4')
Out[29]: array([-736130505], dtype=int32)
```


From that I would conclude, that our file is Big Endian and the ctapipe file is Small Endian.

Am I mistaken?

**Comment by MaxNoe** [comment]
That also fits with the passagage
> 0xD41F8A37 (in C notation, i.e. 3558836791 as an unsigned long or -736130505 as a signed long.
Because in C
```
int a = 0x00ff;
printf(a);
```
is 255.

**Comment by MaxNoe** [comment]
Sorry, I'm stupid. Both files are little endian.

**Comment by MaxNoe** [comment]
Ok, I now test for Endianess and raise `NotImplementedError` for Big Endian byte order. I will put this to won't fix for now.

**Comment by MaxNoe** [comment]
For future reference: `37 8a 1f d4` Is the marker for Little Endian.
