### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/pyeventio#7]
- [x] Remove unsused code
- [x] Rename classes and methods t fit the eventio docs (e.g. `ObjectHeader`)
- [x] Follow styleguide
- [x] Improve bitwise magic

**Comment by dneise** [comment]
With Improve bitwise magic, do you mean something like 0201871aeb8253cc8c337dd7592d7bc74728034e?

**Comment by MaxNoe** [comment]
Yep, i like that a lot better than what we had before.

**Comment by dneise** [comment]
Hm .. explaining lines of code in comments is a much disputed thing... 
can you point to the lines most unclear? all bitshifts?
I can translate all bitshifts into multiplications and divisions ... but it obscures meaning more than it shows it then:

Constructions like this:

    bool(uint32_word & (1 << 16))

are typical for: "If bis 16 of this `word` is set, be True, else be False".

**Comment by dneise** [comment]
I am stupid ... it was full of magic numbers ... and I walk around and think it was nicer now.
magic numbers now removed: 139475d242579e4a6788f1566b0caed52cd1e706

Also I wanted to be smart an make the bit operations in a small amount of operations ...
stupid!

Now it should be possible to understand it 75e51f11e7d9b872614e6e8db072de2eb5596dac

**Comment by MaxNoe** [comment]
Looks good, thanks.
