### ISSUE TITLE
Define API features in functional tests

### ISSUE THREAD

**Issue by dneise** [fact-project/pyeventio#8]
as in e.g.:

 I want to be able to open a file and then iterate only over events with energies higher (or lower) a certain threshold. So I need to get the event headers for all events, without event looking at the photon bunches, since that can be awfully slow depending on the file size and the size of the photon bunches.
Once I have the event headers I needs to be able to access directly those events, which I would like to look at.

I want to be able to iterate over events and be "reuse agnostic", i.e. the next event may be a real event or just a reuse of the same event I just looked at, I don't care .. I don't want to have to use two loops in case the producer decided reuse should be not 1.

I want to be able to use this library to research a new and (currently) unknown eventio object type, i.e. it should have a sane default for unknown types like: return the entire body as a binary blob (e.g. numpy array of bytes or bytes-string or bytes array)

**Comment by dneise** [comment]
I would like to be able to have access to the run footer as soon as I open the file, maybe event throw a warning in case the footer is missing or so. However, there is no way to "jump" to the footer without reading all eventio-headers of the objects in between, since there is no index with jump adresses in eventio.

Other people might like a version better, which has streaming in mind, i.e. the reader reads only as many eventio objects as are needed to return the next event, or what ever the user wanted. 

I would like to have an eventio writer as well, basically for testing.

**Comment by dneise** [comment]
All this stuff I would like to write down as functional tests. Not sure how that looks once these stories are cast in code... 
We will see

**Comment by dneise** [comment]
Corsika eventheaders and runheaders should be namedtuples with Quantitys inside, as we did it in smart_fact_crawler. The reason is, the corsika docu explains these headers contents by their index, and namedtuples allow also indexed access, which is good. People who rather like named access are also served. Everybody's happy

**Comment by MaxNoe** [comment]
Have a look:
https://github.com/fact-project/pyeventio/commit/34b1b7923e8618cab6620857d34feca2e93948b6

**Comment by MaxNoe** [comment]
Done
