### ISSUE TITLE
Current Performance

### ISSUE THREAD

**Issue by dneise** [fact-project/pyeventio#83]
I am currently on the varint_cython branch an test how fast pyeventio and pyhessio iterate through a file.
I use `gamma_test.simtel.gz` since the pyhessio version on my machine cannot read our newer test files.

This are the programs I execute for testing:

`try_pyhessio.py`

```python
#!/usr/bin/env python
# coding: utf-8
import sys
import time
import pyhessio

url = sys.argv[1]

with pyhessio.open_hessio(url) as f:

    start_time = time.time()
    for ee in f.move_to_next_event():
        pass
        # print(ee)
    print('  Duration:', time.time() - start_time)
```

---

`try_hessio_eventsource.py`
```python
#!/usr/bin/env python
import sys
import time
from ctapipe.io.hessioeventsource import HESSIOEventSource

url = sys.argv[1]
source = HESSIOEventSource(input_url=url)

start_time = time.time()
for i, e in enumerate(source):
    # print(e)
    pass
print('  Duration:', time.time() - start_time)
print("i:", i)
```

---

`try_pyeventio.py`

```python
#!/usr/bin/env python
import sys
import time
from eventio import EventIOFile
from eventio.search_utils import yield_all_objects_depth_first

url = sys.argv[1]

start_time = time.time()

try:
    with EventIOFile(url) as f:
        for o, level in yield_all_objects_depth_first(f):
            if hasattr(o, 'parse_data_field'):
                d = o.parse_data_field()
except IndexError:
    pass

print('  Duration:', time.time() - start_time)
```

Below I will put some results

**Comment by dneise** [comment]
called them like:

 for i in `ls try*.py`; do echo; echo $i; ./$i eventio/resources/gamma_test.simtel.gz ; done

and got:
```
09:53 $ for i in `ls try*.py`; do echo; echo $i; ./$i eventio/resources/gamma_test.simtel.gz ; done

try_hessio_eventsource.py
Doing one-time thread-specific warning data initialization.
I/O block extended by 744748 to 1744748 bytes
I/O block extended by 212992 to 1957740 bytes
Wrong number of bytes were read (635256 instead of 1560656)
  Duration: 0.5440869331359863
i: 8

try_pyeventio.py
  Duration: 8.922606468200684

try_pyhessio.py
Doing one-time thread-specific warning data initialization.
I/O block extended by 744748 to 1744748 bytes
I/O block extended by 212992 to 1957740 bytes
Wrong number of bytes were read (635256 instead of 1560656)
  Duration: 0.38321375846862793
```

**Comment by dneise** [comment]
To test the effect of slow gzip in Python is executed them on an unpacked file:

    for i in `ls try*.py`; do echo; echo $i; ./$i eventio/resources/gamma_test.simtel ; done

Results:
```
try_hessio_eventsource.py
Doing one-time thread-specific warning data initialization.
I/O block extended by 744748 to 1744748 bytes
I/O block extended by 212992 to 1957740 bytes
Wrong number of bytes were read (635256 instead of 1560656)
  Duration: 0.29879164695739746
i: 8

try_pyeventio.py
  Duration: 5.163223743438721

try_pyhessio.py
Doing one-time thread-specific warning data initialization.
I/O block extended by 744748 to 1744748 bytes
I/O block extended by 212992 to 1957740 bytes
Wrong number of bytes were read (635256 instead of 1560656)
  Duration: 0.130279541015625
```

**Comment by dneise** [comment]
# Current state in short words:

We are currently a factor 16 or 17 (independent of gzip or not) slower than the hessio_eventsource (and we do not even fill a `DataContainer` yet). 

If I guessed correctly that there are about 8 events in the gamma_test file, then the HESSIOEventSource seems to deliver about 18 events per second. Accordingly  we seem to deliver ~1 event per sec.

However my try_pyeveentio.py seems to be a bit unfair for us, since we most probably do not have to parse all of objects...

**Comment by dneise** [comment]
example call: 

    ./try_pyeventio.py eventio/resources/gamma_test.simtel.gz & psrecord --plot=try_pyeventio.png $!


try_hessio_eventsource

![try_hessio_eventsource](https://user-images.githubusercontent.com/8200858/49364406-8fc79c00-f6e4-11e8-969c-810d105cd208.png)


----

try_pyeventio

![try_pyeventio](https://user-images.githubusercontent.com/8200858/49364413-92c28c80-f6e4-11e8-8750-b4f0576a78f8.png)

**Comment by dneise** [comment]
When using `psrecord` it seems to be important to define the `interval` ... otherwise the CPU percentage is not measured correctly .. it looks as if the processes would utilize a few thousand percent sometime ... :-(

**Comment by dneise** [comment]
If we skip the `History` object in `try_pyeventio.py` runtime is reduced from 9sec to 7sec  (and from 5.2 to 4.2sec for unpacked). So without parsing the History we are at a factor ~13 slower.

**Comment by MaxNoe** [comment]
Running try_simtel_file using cprofile for a prod3b largish (700MB gunzipped) file yields these runtimes for the parse data method:

```
#calls cumtime type class
400000   3.698 2021 MCEvent
  3261   2.696 2013 ADCSamp
 20000   2.045 2020 MCShower
   586   0.646 2026 MCPeSum
  3192   0.524 2014 TelImage
  3910   0.268 2011 EvtHead
   567   0.134 2022 TelMoni
  3843   0.115 2027 PixelList
   567   0.099 2002 CamSettings
  3762   0.071 21xx TrackEvent
   387   0.055 2009 CentEvent
   649   0.052 2012 ADCSum
   567   0.044 2004 Pixelset
   567   0.028 2023 LasCal
     1   0.000 2000 RunHeader
```

**Comment by dneise** [comment]
This is mostly outdated.
Currently we reach something <2 ... while mem consumption is really nice.
